FROM p4lang/behavioral-model:stable

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends \
      vim \
      ca-certificates \
      build-essential \
      curl \
      git \
      iproute2 \
      iputils-ping \
      traceroute \
      tcpdump \
      iperf3 \
      dnsutils \
      net-tools \
      ethtool
