listening-port: 6000
SMO-ip: 127.0.0.1
SMO-port: 5000
interfaces:
  - id: ran-br-0
    type: tofino
    port: 156

  - id: ran-br-1
    type: tofino
    port: 156

  - id: t1-xtreme-0
    type: tofino
    port: 142

nodes:
  - id: "t1"
    sriov-capable: false
  - id: "xtreme"
    sriov-capable: true
    sriov-vf-name: "intel.com/intel_sriov_netdevice"

predeployed-nfrs:
  - instance-id: "nfr-t1"
    node: "t1"
    controlplane-ip: "10.5.15.2"
    controlplane-port: "5555"
    static-mac: "02:33:44:55:66:77"
    interfaces: ["ran-br-0", "ran-br-1", "t1-epyc1-0"]

predeployed-tas: []
predeployed-nfs: []

predeployed-afs:
  - instance-id: "ran"
    name: "RAN"
    version: "1.0"
    node: "t1"
    domain: "external"
    is-ue: true
    static-ips: ["172.20.50.7", "172.20.50.8"]
    extra-ueids: [[], ["172.20.50.9"]]
