apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfrouter-bmv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfrouter-bmv2
  template:
    metadata:
      labels:
        app: nfrouter-bmv2
    spec:
      initContainers:
      - name: switch
        image: desire6g/nfrouter-bmv2:latest
        imagePullPolicy: Never
        restartPolicy: Always
        securityContext:
          privileged: true
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "trap : TERM INT; sleep infinity & wait" ]
        resources:
          limits:
            memory: 4Gi
            nvidia.com/cx6dx_vf: '1'
          requests:
            memory: 4Gi
            nvidia.com/cx6dx_vf: '1'
      containers:
      - name: nfrouter-bmv2
        image: desire6g/nfrouter-controlplane:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "trap : TERM INT; sleep infinity & wait" ]
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
