listening-port: 6000
SMO-ip: 127.0.0.1
SMO-port: 5000
interfaces:
  - id: src-br-0
    type: tofino
    port: 156 # 49

  - id: site1-site2-0
    type: tofino
    port: 188 # 51

nodes:
  - id: "t1"
    sriov-capable: false

predeployed-nfrs:
  - instance-id: "nfr-t1"
    node: "t1"
    controlplane-ip: "10.30.7.53"
    controlplane-port: "5555"
    static-mac: "02:33:44:55:66:77"
    int-enabled: true
    interfaces: ["src-br-0", "site1-site2-0"]

predeployed-tas:
  - id: "site2"
    transport-type: "internal"
    transport-node: "t1"
    transport-interface: "site1-site2-0"
    nfr-mac: "02:44:44:44:44:44"

predeployed-nfs: []

predeployed-afs:
  - instance-id: "src"
    id: "iperf3"
    name: "AR source app"
    version: "1.0"
    node: "t1"
    domain: "internal"
    is-ue: true
    static-nfids: [42, 43]
    static-macs: ["02:22:33:44:55:66"]
    static-ips: ["192.168.1.4"]

