---
- name: Init k8s cluster
  hosts: k8s_controls, k8s_workers
  tasks:
    - name: Install kubernetes
      ansible.builtin.import_role:
        name: install-k8s-deps
      tags: install

    - name: Init k8s cluster
      ansible.builtin.import_role:
        name: init-k8s-cluster
      tags: init

    - name: Install d6g dependencies
      ansible.builtin.import_role:
        name: install-d6g-deps
      tags: d6gdeps
