apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf3
        image: desire6g/iperf3:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "trap : TERM INT; sleep infinity & wait" ]
