apiVersion: apps/v1
kind: Deployment
metadata:
  name: alternator-bmv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alternator-bmv2
  template:
    metadata:
      labels:
        app: alternator-bmv2
    spec:
      containers:
      - name: alternator-bmv2
        image: desire6g/alternator-bmv2:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "trap : TERM INT; sleep infinity & wait" ]
        command: [ "/bin/bash", "/src/alternator/data-plane/entrypoint.sh", "alternator" ]
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi
